redis_url: redis://localhost:6379/

lybercore_log: 'log/lybercore.log'

# where to find the deposit bag to be preserved
transfer_object:
  from_dir: '/dor/export/'

moab:
  # storage_roots:
  #   - '/services-disk/store1'
  #   - '/services-disk/store2'
  storage_trunk: 'sdr2objects'
  deposit_trunk: 'deposit'
  path_method: 'druid_tree'

preservation_catalog:
  url: 'http://localhost:3000'
  token: 'YOUR_TOKEN_HERE'

email_addresses:
  discussion_list: 'user@discussion_list.org'
  user_list: 'user@user_list.org'

dor_services:
  url:  'https://dor-services-test.stanford.test'
  token: secret-token